### ISSUE TITLE
Please consider merging your work

### ISSUE THREAD

**Issue by pcav** [nextgis/qgis_copy_coords#2]
Your plugin is part of a group of plugins with very similar functionalities:
http://plugins.qgis.org/plugins/latlontools/
http://plugins.qgis.org/plugins/zoomtopoint/
http://plugins.qgis.org/plugins/zoomtocoordinates/
http://plugins.qgis.org/plugins/copy_coords/

See a detailed analysis here:
https://lists.osgeo.org/pipermail/qgis-developer/2016-June/043164.html
It would be great if you could cooperate to create a new plugin, merging all your work. This will certainly result in a more robust software, less duplication of efforts, and especially less confusion for users: it is currently quite difficult for them to understand which one to use.
If successful, it would be reasonbable to insert this new plugin into QGIS core.

**Comment by simgislab** [comment]
well, author of the comparison obviously didn't read the description of the plugin, and 

> The major difference with LatLonTools is that it assumes degrees as input
> and output no matter what the project CRS is and it formats them in the
> order of on-line maps.

is simply wrong. I quote from the description of the Copy_coords:

> Use SHIFT to copy coordinates in EPSG:4326 (WGS 1984) independently from what your current CRS is.

He chose to develop a new plugin instead of sending an easy fix to current implementation (though it's not even needed AFAIK). If he doesn't want to collaborate, why would I go to him asking for collaboration?
